name: monitoreo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.0
  excel: ^2.0.6
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  open_file: ^3.3.2
  share_plus: ^7.2.1
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  path: ^1.9.1
  uuid: ^4.5.1
  
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/