// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZmiOXM2C2wgCjBBBiN6e4EP9WkvOKwns',
    appId: '1:969024106320:web:7d0f7588d84290f31e4655',
    messagingSenderId: '969024106320',
    projectId: 'monitoreo-y-mantenimiento',
    authDomain: 'monitoreo-y-mantenimiento.firebaseapp.com',
    storageBucket: 'monitoreo-y-mantenimiento.firebasestorage.app',
    measurementId: 'G-FWDGXVJJ0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuZ6SA_7JVLGc7ZVHz0lpjSkCR184oah8',
    appId: '1:969024106320:android:56f25ed52596b4521e4655',
    messagingSenderId: '969024106320',
    projectId: 'monitoreo-y-mantenimiento',
    storageBucket: 'monitoreo-y-mantenimiento.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWyG8LJDKa5thNFDGGIDy5m1_YNPAV0HA',
    appId: '1:969024106320:ios:b1d4eb22be3ad9ef1e4655',
    messagingSenderId: '969024106320',
    projectId: 'monitoreo-y-mantenimiento',
    storageBucket: 'monitoreo-y-mantenimiento.firebasestorage.app',
    iosBundleId: 'com.example.monitoreo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWyG8LJDKa5thNFDGGIDy5m1_YNPAV0HA',
    appId: '1:969024106320:ios:b1d4eb22be3ad9ef1e4655',
    messagingSenderId: '969024106320',
    projectId: 'monitoreo-y-mantenimiento',
    storageBucket: 'monitoreo-y-mantenimiento.firebasestorage.app',
    iosBundleId: 'com.example.monitoreo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZmiOXM2C2wgCjBBBiN6e4EP9WkvOKwns',
    appId: '1:969024106320:web:ffe8f0382d3323931e4655',
    messagingSenderId: '969024106320',
    projectId: 'monitoreo-y-mantenimiento',
    authDomain: 'monitoreo-y-mantenimiento.firebaseapp.com',
    storageBucket: 'monitoreo-y-mantenimiento.firebasestorage.app',
    measurementId: 'G-6DDMZKTE4Y',
  );
}